[package]
name = "portredirect"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "*"
quinn = "0.11.6"
rcgen = { version = "0.13.1", features = ["pem", "crypto"] }
rustls = { version = "0.23.19", features = ["ring"] }
rustls-pemfile = "2.2.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "*"