#!/usr/bin/env python3
"""
This script parses and analyzes log files generated by connestion_stress_test.py.

Dependencies (Arch Linux):
 pacman -S python-matplotlib python-pandas python-scipy

Usage:
 python3 tests/cst_datacruncher.py testlogs/prrs_full_e2e_connection_stress_test_*/cst_*

Unit Test:
 python3 -m unittest test_cst_datacruncher.py
"""
import re
import sys
import os
import argparse
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt

# Regex to remove ANSI escape codes
ansi_escape = re.compile(r"\x1B\[[0-?]*[ -/]*[@-~]")

# Regex to parse a generic log line
log_line_re = re.compile(
    r"^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d+)\s+(?P<level>\S+):\s+(?P<message>.*)$"
)


def parse_filename(filename):
    """
    Extracts test details from the filename.
    Expected format: cst_(baseline|benchmark)_<concurrency>_<transfersize>.log
    e.g., cst_baseline_1c_1gb.log or cst_benchmark_50c_20mb.log
    """
    base = os.path.basename(filename)
    parts = base.split("_")
    if len(parts) >= 4:
        mode = parts[1]
        concurrency = parts[2]
        transfersize = parts[3].split(".")[0]  # remove extension
        return mode, concurrency, transfersize
    return None, None, None


def parse_transfer_metrics(message):
    """
    Parses the transfer metrics from a log message using substring splitting.
    Expected format (after ANSI codes are removed):
      UP: <up_mb> MB transferred (<up_pct>% complete) | Speed: min: <up_min> MB/s, max: <up_max> MB/s, avg: <up_avg> MB/s
      || DOWN: <down_mb> MB transferred (<down_pct>% complete) | Speed: min: <down_min> MB/s, max: <down_max> MB/s, avg: <down_avg> MB/s
    """
    try:
        # Split into UP and DOWN parts using the "||" delimiter.
        parts = message.split("||")
        if len(parts) < 2:
            return None
        up_part = parts[0].strip()
        down_part = parts[1].strip()

        # --- Parse UP part ---
        # Example:
        # "UP: 447.69 MB transferred (22.38% complete) | Speed: min: 74.58 MB/s, max: 177.97 MB/s, avg: 141.94 MB/s"
        up_mb_str = up_part.split("MB transferred")[0].split("UP:")[1].strip()
        up_mb = float(up_mb_str)
        pct_section = up_part.split("MB transferred")[1]
        start = pct_section.find("(")
        end = pct_section.find("%")
        up_pct = float(pct_section[start + 1 : end].strip())
        up_speed_section = up_part.split("|")[-1]
        if "Speed:" in up_speed_section:
            up_speed_section = up_speed_section.split("Speed:")[1]
        speed_parts = up_speed_section.split(",")
        up_min = float(speed_parts[0].split("min:")[1].strip().split(" ")[0])
        up_max = float(speed_parts[1].split("max:")[1].strip().split(" ")[0])
        up_avg = float(speed_parts[2].split("avg:")[1].strip().split(" ")[0])

        # --- Parse DOWN part ---
        # Example:
        # "DOWN: 256.19 MB transferred (12.81% complete) | Speed: min: 0.11 MB/s, max: 433.30 MB/s, avg: 123.19 MB/s"
        down_mb_str = down_part.split("MB transferred")[0].split("DOWN:")[1].strip()
        down_mb = float(down_mb_str)
        pct_section = down_part.split("MB transferred")[1]
        start = pct_section.find("(")
        end = pct_section.find("%")
        down_pct = float(pct_section[start + 1 : end].strip())
        down_speed_section = down_part.split("|")[-1]
        if "Speed:" in down_speed_section:
            down_speed_section = down_speed_section.split("Speed:")[1]
        speed_parts = down_speed_section.split(",")
        down_min = float(speed_parts[0].split("min:")[1].strip().split(" ")[0])
        down_max = float(speed_parts[1].split("max:")[1].strip().split(" ")[0])
        down_avg = float(speed_parts[2].split("avg:")[1].strip().split(" ")[0])

        return (
            up_mb,
            up_pct,
            up_min,
            up_max,
            up_avg,
            down_mb,
            down_pct,
            down_min,
            down_max,
            down_avg,
        )
    except Exception as e:
        print("Error parsing transfer metrics:", e)
        return None


def parse_log_file(filepath):
    data = []
    mode, concurrency, transfersize = parse_filename(filepath)

    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            # Remove ANSI codes
            clean_line = ansi_escape.sub("", line).strip()
            if not clean_line:
                continue

            # Parse the generic log line
            m = log_line_re.match(clean_line)
            if not m:
                continue

            log_entry = m.groupdict()
            try:
                # Convert timestamp to datetime
                log_entry["timestamp"] = datetime.strptime(
                    log_entry["timestamp"], "%Y-%m-%d %H:%M:%S,%f"
                )
            except Exception as e:
                print(f"Timestamp parsing error in file {filepath}: {e}")
                continue

            log_entry["file"] = os.path.basename(filepath)
            log_entry["mode"] = mode
            log_entry["concurrency"] = concurrency
            log_entry["transfersize"] = transfersize
            # Default event type is the raw message
            log_entry["event"] = "message"
            # Initialize metric fields as None
            for key in [
                "up_mb",
                "up_pct",
                "up_min",
                "up_max",
                "up_avg",
                "down_mb",
                "down_pct",
                "down_min",
                "down_max",
                "down_avg",
            ]:
                log_entry[key] = None

            # If the message contains transfer metrics, try to parse them.
            if "UP:" in log_entry["message"] and "DOWN:" in log_entry["message"]:
                parsed = parse_transfer_metrics(log_entry["message"])
                if parsed:
                    (
                        log_entry["up_mb"],
                        log_entry["up_pct"],
                        log_entry["up_min"],
                        log_entry["up_max"],
                        log_entry["up_avg"],
                        log_entry["down_mb"],
                        log_entry["down_pct"],
                        log_entry["down_min"],
                        log_entry["down_max"],
                        log_entry["down_avg"],
                    ) = parsed
                    log_entry["event"] = "transfer"
            data.append(log_entry)
    return data


def load_logs(filepaths):
    all_data = []
    for filepath in filepaths:
        print(f"Processing file: {filepath}")
        all_data.extend(parse_log_file(filepath))
    return pd.DataFrame(all_data)


def plot_transfer_timeseries(df):
    # Filter for transfer events only
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found to plot.")
        return

    # Plot UP and DOWN average speeds over time for each file
    files = df_transfer["file"].unique()
    plt.figure(figsize=(12, 6))
    for f in files:
        df_file = df_transfer[df_transfer["file"] == f]
        plt.plot(df_file["timestamp"], df_file["up_avg"], marker="o", label=f"{f} UP")
        plt.plot(
            df_file["timestamp"],
            df_file["down_avg"],
            marker="x",
            linestyle="--",
            label=f"{f} DOWN",
        )
    plt.xlabel("Timestamp")
    plt.ylabel("Average Speed (MB/s)")
    plt.title("Transfer Average Speeds Over Time")
    plt.legend(fontsize="small", loc="upper left")
    plt.grid(True)
    plt.tight_layout()
    output_file = "transfer_timeseries.png"
    plt.savefig(output_file)
    print(f"Time series plot saved as {output_file}")
    plt.close()


def plot_speed_boxplot(df):
    # Boxplot for UP average speeds by configuration
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for boxplot.")
        return

    df_transfer["config"] = (
        df_transfer["mode"]
        + "_"
        + df_transfer["concurrency"]
        + "_"
        + df_transfer["transfersize"]
    )
    plt.figure(figsize=(12, 6))
    df_transfer.boxplot(column="up_avg", by="config", grid=True, rot=45)
    plt.xlabel("Test Configuration")
    plt.ylabel("UP Avg Speed (MB/s)")
    plt.title("Distribution of UP Average Speeds by Configuration")
    plt.suptitle("")
    plt.tight_layout()
    output_file = "speed_boxplot.png"
    plt.savefig(output_file)
    print(f"Boxplot (UP) saved as {output_file}")
    plt.close()


def plot_down_boxplot(df):
    # Boxplot for DOWN average speeds by configuration
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for DOWN boxplot.")
        return

    df_transfer["config"] = (
        df_transfer["mode"]
        + "_"
        + df_transfer["concurrency"]
        + "_"
        + df_transfer["transfersize"]
    )
    plt.figure(figsize=(12, 6))
    df_transfer.boxplot(column="down_avg", by="config", grid=True, rot=45)
    plt.xlabel("Test Configuration")
    plt.ylabel("DOWN Avg Speed (MB/s)")
    plt.title("Distribution of DOWN Average Speeds by Configuration")
    plt.suptitle("")
    plt.tight_layout()
    output_file = "down_speed_boxplot.png"
    plt.savefig(output_file)
    print(f"Boxplot (DOWN) saved as {output_file}")
    plt.close()


def plot_cumulative_transfer(df):
    # Plot cumulative UP and DOWN transferred over time for each file.
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for cumulative plot.")
        return

    files = df_transfer["file"].unique()
    plt.figure(figsize=(12, 6))
    for f in files:
        df_file = df_transfer[df_transfer["file"] == f].sort_values("timestamp")
        # Drop rows with missing values
        df_file = df_file.dropna(subset=["up_mb", "down_mb"])
        if df_file.empty:
            continue
        cum_up = df_file["up_mb"].cumsum()
        cum_down = df_file["down_mb"].cumsum()
        plt.plot(df_file["timestamp"], cum_up, marker="o", label=f"{f} UP cumulative")
        plt.plot(
            df_file["timestamp"],
            cum_down,
            marker="x",
            linestyle="--",
            label=f"{f} DOWN cumulative",
        )
    plt.xlabel("Timestamp")
    plt.ylabel("Cumulative Data Transferred (MB)")
    plt.title("Cumulative Data Transfer Over Time")
    plt.legend(fontsize="small", loc="upper left")
    plt.grid(True)
    plt.tight_layout()
    output_file = "cumulative_transfer.png"
    plt.savefig(output_file)
    print(f"Cumulative transfer plot saved as {output_file}")
    plt.close()


def plot_aggregated_bar_chart(df):
    # Aggregated bar charts with error bars for average UP and DOWN speeds by configuration.
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for aggregated bar chart.")
        return

    df_transfer["config"] = (
        df_transfer["mode"]
        + "_"
        + df_transfer["concurrency"]
        + "_"
        + df_transfer["transfersize"]
    )
    # Group by config and calculate mean and std.
    grouped = df_transfer.groupby("config").agg(
        {"up_avg": ["mean", "std"], "down_avg": ["mean", "std"]}
    )
    # Flatten the MultiIndex columns.
    grouped.columns = ["_".join(col) for col in grouped.columns]
    grouped = grouped.reset_index()

    # Bar chart for UP average speeds.
    plt.figure(figsize=(12, 6))
    plt.bar(
        grouped["config"], grouped["up_avg_mean"], yerr=grouped["up_avg_std"], capsize=5
    )
    plt.xlabel("Test Configuration")
    plt.ylabel("UP Avg Speed (MB/s)")
    plt.title("Average UP Speeds by Configuration with Error Bars")
    plt.xticks(rotation=45)
    plt.tight_layout()
    output_file = "aggregated_up_bar_chart.png"
    plt.savefig(output_file)
    print(f"Aggregated UP bar chart saved as {output_file}")
    plt.close()

    # Bar chart for DOWN average speeds.
    plt.figure(figsize=(12, 6))
    plt.bar(
        grouped["config"],
        grouped["down_avg_mean"],
        yerr=grouped["down_avg_std"],
        capsize=5,
    )
    plt.xlabel("Test Configuration")
    plt.ylabel("DOWN Avg Speed (MB/s)")
    plt.title("Average DOWN Speeds by Configuration with Error Bars")
    plt.xticks(rotation=45)
    plt.tight_layout()
    output_file = "aggregated_down_bar_chart.png"
    plt.savefig(output_file)
    print(f"Aggregated DOWN bar chart saved as {output_file}")
    plt.close()


def plot_throughput_vs_concurrency(df):
    # Scatter plot of average speeds vs. number of simultaneous connections.
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for throughput vs. concurrency.")
        return

    # Extract numeric value from concurrency (e.g., "50c" -> 50).
    def extract_concurrency(val):
        try:
            return int(val.lower().replace("c", ""))
        except Exception:
            return None

    df_transfer["concurrency_num"] = df_transfer["concurrency"].apply(
        extract_concurrency
    )
    df_transfer = df_transfer.dropna(subset=["concurrency_num"])

    plt.figure(figsize=(12, 6))
    modes = df_transfer["mode"].unique()
    markers = {"baseline": "o", "benchmark": "x"}
    for mode in modes:
        df_mode = df_transfer[df_transfer["mode"] == mode]
        plt.scatter(
            df_mode["concurrency_num"],
            df_mode["up_avg"],
            marker=markers.get(mode, "o"),
            label=f"{mode} UP",
        )
        plt.scatter(
            df_mode["concurrency_num"],
            df_mode["down_avg"],
            marker=markers.get(mode, "x"),
            label=f"{mode} DOWN",
        )
    plt.xlabel("Number of Simultaneous Connections")
    plt.ylabel("Average Speed (MB/s)")
    plt.title("Throughput vs. Number of Connections")
    plt.legend(fontsize="small", loc="upper left")
    plt.grid(True)
    plt.tight_layout()
    output_file = "throughput_vs_concurrency.png"
    plt.savefig(output_file)
    print(f"Throughput vs. concurrency plot saved as {output_file}")
    plt.close()


def plot_throughput_density(df):
    # Density plots for UP and DOWN average speeds, separated by mode.
    df_transfer = df[df["event"] == "transfer"].copy()
    if df_transfer.empty:
        print("No transfer events found for density plot.")
        return

    modes = df_transfer["mode"].unique()
    plt.figure(figsize=(12, 6))
    for mode in modes:
        df_mode = df_transfer[df_transfer["mode"] == mode]
        # Plot density for UP and DOWN speeds.
        df_mode["up_avg"].plot(kind="density", label=f"{mode} UP")
        df_mode["down_avg"].plot(kind="density", label=f"{mode} DOWN", linestyle="--")
    plt.xlabel("Average Speed (MB/s)")
    plt.title("Density Plot of Throughput (UP and DOWN) by Mode")
    plt.legend(fontsize="small")
    plt.grid(True)
    plt.tight_layout()
    output_file = "throughput_density.png"
    plt.savefig(output_file)
    print(f"Throughput density plot saved as {output_file}")
    plt.close()


def main():
    parser = argparse.ArgumentParser(
        description="Analyze benchmark log files and plot transfer metrics."
    )
    parser.add_argument("files", nargs="+", help="Paths to log files")
    args = parser.parse_args()

    df = load_logs(args.files)

    if df.empty:
        print("No log data was parsed. Exiting.")
        sys.exit(1)

    print("Sample parsed data:")
    print(df.head())

    # Plot time series for transfer speeds and save as PNG.
    plot_transfer_timeseries(df)
    # Plot boxplot for UP average speeds.
    plot_speed_boxplot(df)
    # Plot boxplot for DOWN average speeds.
    plot_down_boxplot(df)
    # Plot cumulative transfer over time.
    plot_cumulative_transfer(df)
    # Plot aggregated bar charts for UP and DOWN speeds.
    plot_aggregated_bar_chart(df)
    # Plot throughput vs. number of connections.
    plot_throughput_vs_concurrency(df)
    # Plot density plots for throughput distributions.
    plot_throughput_density(df)


if __name__ == "__main__":
    main()
