name: Full End-to-End Simple Test (iperf3)
# This test checks that portredirect runs and doesn't blatantly crash or exits with an error.
# Also added a debug tmate hook.

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
env:
  CARGO_TERM_COLOR: always
jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y bats iperf3
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Run BATS test(s)
        # show passing test's output because we only do one test, so no clutter
        run: bats --print-output-on-failure --show-output-of-passing-tests --gather-test-outputs-in ./bats-logs tests/full_e2e_test.bats
      - name: Show Log Files
        if: always()
        run: |
          echo "========== testlogs =========="
          tail -n+0 ./testlogs/*/* || true
          echo "========== bats-logs =========="
          tail -n+0 ./bats-logs/* || true
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: portredirect-e2e-test-logs
          path: |
            ./testlogs
            ./bats-logs
