name: Full End-to-End Netcat Data Integrity Checks

on:
  push:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run BATS test(s)
        run: bats tests/full_e2e_netcat_checksum.bats

      - name: Show Log Files
        if: always()
        run: |
          echo "========== metrics*.log =========="
          cat metrics*.log || true
          echo "========== server.log =========="
          cat server.log || true
          echo "========== client.log =========="
          cat client.log || true
          echo "========== iperf_server.log =========="
          cat iperf_server.log || true

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: portredirect-e2e-benchmark-logs
          path: |
            server.log
            client.log
            iperf_server.log
            metrics*.log
