name: Full End-to-End Test
# similar to the benchmark workflow, but with a few checks removed

on:
  push:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install iperf3 and bats
        run: |
          sudo apt-get update
          sudo apt-get install -y iperf3
          sudo apt-get install -y bats

      - name: Run BATS test(s)
        run: bats tests/full_e2e_test.bats

      - name: Show Log Files on Failure
        if: failure()
        run: |
          echo "========== server.log =========="
          cat server.log || true
          echo "========== client.log =========="
          cat client.log || true
          echo "========== iperf_server.log =========="
          cat iperf_server.log || true

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            server.log
            client.log
            iperf_server.log

